# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BaseProjectF2G' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftyJSON'	
	pod 'SnapKit'
	pod 'NotificationBannerSwift'
	pod 'Localize-Swift'

  # Pods for BaseProjectF2G

  target 'BaseProjectF2GTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseProjectF2GUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
